import * as mongoos from 'mongoose';
import { DbCacheableModel } from 'src/utilities/mongoDbLongTermCaching/mongoDbLongTermCaching.types';

export const TeamSchema = new mongoos.Schema({
    apiId: {type: Number, required: true},
    teamName: {type: String, required: true},
    shortTeamName: {type: String, required: true},
    sportName: {type: String, required: true},
    leagueName: {type: String, required: true},
    leagueId: {type: Number, required: true},
    stadiumName: {type: String, required: true},
    stadiumLocation: {type: String, required: true},
    teamBadgeUrl: {type: String, required: true},
    teamLogoUrl: {type: String, required: true},
    teamBannerUrl: {type: String, required: true},
    insertTimestamp: {type: Date, required: true},
    insertExpirationDate: {type: Date, required: true}
});

export interface Team extends mongoos.Document, DbCacheableModel {
    apiId: number,
    teamName: string,
    shortTeamName: string,
    sportName: string,
    leagueName: string,
    leagueId: number,
    stadiumName: string,
    stadiumLocation: string,
    teamBadgeUrl: string,
    teamLogoUrl: string,
    teamBannerUrl: string,
}

export interface SportDbTeam {
    idTeam: number,
    idSoccerXML: string,
    idAPIfootball: number,
    intLoved: number,
    strTeam: string,
    strTeamShort: string,
    strAlternate: string,
    intFormedYear: number,
    strSport: string,
    strLeague: string,
    idLeague: number,
    strLeague2: string,
    idLeague2: number,
    strLeague3: string,
    idLeague3: number,
    strLeague4: string,
    idLeague4: number,
    strLeague5: string,
    idLeague5: number,
    strLeague6: string,
    idLeague6: number,
    strLeague7: string,
    idLeague7: number,
    strDivision: string,
    strManager: string,
    strStadium: string,
    strKeywords: string,
    strRSS: string,
    strStadiumThumb: string,
    strStadiumDescription: string,
    strStadiumLocation: string,
    intStadiumCapacity: number,
    strWebsite: string,
    strFacebook: string,
    strTwitter: string,
    strInstagram: string,
    strDescriptionEN: string,
    strDescriptionDE: string,
    strDescriptionFR: string,
    strDescriptionCN: string,
    strDescriptionIT: string,
    strDescriptionJP: string,
    strDescriptionRU: string,
    strDescriptionES: string,
    strDescriptionPT: string,
    strDescriptionSE: string,
    strDescriptionNL: string,
    strDescriptionHU: string,
    strDescriptionNO: string,
    strDescriptionIL: string,
    strDescriptionPL: string,
    strGender: string,
    strCountry: string,
    strTeamBadge: string,
    strTeamJersey: string,
    strTeamLogo: string,
    strTeamFanart1:string,
    strTeamFanart2:string,
    strTeamFanart3:string,
    strTeamFanart4:string,
    strTeamBanner: string,
    strYoutube: string,
    strLocked: string
}
